// vueadmin/src/components/ViewHome.vue
<template>
  <div id='view-home' class='view'>
      Welcome to jtree.
      <div style='padding-top: 1rem; color: #888'>0.7.18</div>
  </div>
</template>

<script>
export default {
  name: 'ViewHome',
  props: {
    msg: String
  }
}
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>

// vueadmin/src/webcomponents/ViewHome.js
class ViewHome extends HTMLElement {
    connectedCallback() {
      this.innerHTML = `
      <div id='view-home' class='view'>
          Welcome to jtree.
          <div style='padding-top: 1rem; color: #888'>0.7.17</div>
      </div>
      `;
    }
}

window.customElements.define('view-home', ViewHome);
