// vueadmin/src/components/ViewApp.vue
<template>
    <div>
        <h2 class='text-muted'>App: <span style='color: #000' id='view-app-id'>{{app.shortId}}</span></h2>
        <h6 id='view-app-fullId' class='text-muted'>{{app.id}}</h6>

        <div class="view-buttons btn-group">
            <button class="btn btn-outline-primary btn-sm" onclick='jt.startSessionWithApp()'>
                <i class="fa fa-play"></i>&nbsp;&nbsp;Start session
            </button>
        </div>

        <div class="view-buttons btn-group">
            <button class="btn btn-outline-secondary btn-sm" onclick='jt.appEdit()'>
                <i class="fa fa-edit"></i>&nbsp;&nbsp;Edit...
            </button>
            <button class="btn btn-outline-secondary btn-sm" onclick='jt.appRename()'>
                &nbsp;&nbsp;Rename / Move...
            </button>
        </div>

        <div class="view-buttons btn-group">
            <button class="btn btn-outline-danger btn-sm" onclick='jt.deleteApp()'>
                <i class="fa fa-trash"></i>&nbsp;&nbsp;Delete...
            </button>
        </div>

        <div id='view-app-edit' class='subview app-tab hidden'>
            <div class="btn-group">
                <button type="submit" class="btn btn-sm btn-outline-primary" onclick='jt.saveAppAndView();'>
                    <i class="fa fa-save"></i>&nbsp;Save and view
                </button>
                <button type="submit" class="btn btn-outline-secondary btn-sm" onclick='jt.saveApp();'>
                    <i class="fa fa-save"></i>&nbsp;Save
                </button>
                <button type="submit" class="btn btn-outline-secondary btn-sm" onclick='setView("app")'>
                    <i class="fa fa-times"></i>&nbsp;Cancel
                </button>
            </div>

            <div class="form-group row">
                <label for="edit-app-id" class="col-sm-2 col-form-label">Id</label>
                <div class="col-sm-10">
                    <input type="text" style='max-width: 20rem;' class="form-control" id="edit-app-id" placeholder="Id">
                </div>
            </div>
        </div>
        <view-app-preview></view-app-preview>
    </div>
</template>

<script>

export default {
  name: 'ViewApp',
  data() {
    return {
        app: this.$store.state.app
    }
  },
}

import jt from '@/webcomps/jtree.js'
import 'jquery'

let $ = window.jQuery;

jt.resizeIFrameToFitContent = function(iframe) {
    $(iframe).prop('height', null);
    iframe.height = iframe.contentWindow.document.documentElement.offsetHeight + 36;
    console.log('setting size to ' + iframe.width + ' / ' + iframe.height);
}

jt.appShowOptions = function() {
    // eslint-disable-next-line no-undef
    jt.setEditAppOptionsData(appDefn, options, 'jt.saveSessionAppOptions()');
    $('#editAppOptionsModal').modal('show');
}

jt.openApp = function(appId) {
    var app = jt.app(appId);

    jt.editor.reset();
    jt.editor.addFile(app.id, app.appjs, 'ace/mode/javascript');

    jt.editor.selectFile(app.id);

    jt.setEditAppOptionsData(app, app.options, jt.updateAppPreview);

    window.vue.$store.commit('setApp', app);

    jt.updateAppPreview();

    $('#view-app-tree').empty();

    jt.showPanelNew('App', 'ViewApp');
}

jt.appRename = function() {
    let appId = $('#view-app-fullId').text();
    $('#rename-app-input').val(appId);
    $('#renameAppModal').modal('show');
    $('#rename-app-input').focus();
}

jt.appEdit = function() {
    $('#editAppModal').modal('show');
}

jt.deleteApp = function() {
    var appId = $('#view-app-fullId').text();
    jt.confirm(
        'Are you sure you want to delete App ' + appId + '?',
        function() {
            jt.addLog('Deleting App ' + appId + '.');
            let cb = function() {
                jt.addLog('FINISHED: Deleting App ' + appId + '.');
            }
            jt.socket.emit('deleteApp', appId, cb);
            jt.setView('apps');
        }
    );
}

jt.saveApp = function() {
    var app = {};
    app.origId = $('#view-app-fullId').text();
    app.id = $('#edit-app-id').val();
    var editor = window.ace.edit("edit-app-appjs");
    app.appjs = editor.getValue();

    var editorCH = window.ace.edit("edit-app-clienthtml");
    app.clientHTML = editorCH.getValue();

    jt.socket.emit('saveApp', app);

}

jt.saveAppAndView = function() {
    jt.saveApp();
    jt.setView('app');
}

</script>

// client/internal/clients/admin/vue/webcomponents/ViewApp.js
class ViewApp extends HTMLElement {
    connectedCallback() {
      this.innerHTML = `
      <div id='view-app' class='view hidden'>
          <h2 id='view-app-id'></h2>
          <h6 id='view-app-fullId' class='text-muted'></h6>

          <div class="view-buttons btn-group">
          <button class="btn btn-outline-primary btn-sm" onclick='jt.startSessionWithApp()'>
              <i class="fa fa-play"></i>&nbsp;&nbsp;Start session
          </button>
      </div>

          <div class="view-buttons btn-group">
                <button class="btn btn-outline-success btn-sm" onclick='jt.appEdit()'>
                    <i class="fa fa-file-code"></i>&nbsp;&nbsp;Code...
                </button>
                <button class="btn btn-outline-success btn-sm" onclick='jt.appShowOptions()'>
                    <i class="fa fa-cog"></i>&nbsp;&nbsp;Options...
                </button>
            </div>

        <div class="view-buttons btn-group">
                <button class="btn btn-outline-secondary btn-sm" onclick='jt.startSessionWithApp()'>
                    <i class="fa fa-plus"></i>&nbsp;&nbsp;Add variable
                </button>
                <button class="btn btn-outline-secondary btn-sm" onclick='jt.appEdit()'>
                    <i class="fa fa-plus"></i>&nbsp;&nbsp;Add stage
                </button>
                <button class="btn btn-outline-secondary btn-sm" onclick='jt.appShowOptions()'>
                    <i class="fa fa-plus"></i>&nbsp;&nbsp;Add function
                </button>
            </div>
        <div class="view-buttons btn-group">
                <button class="btn btn-outline-secondary btn-sm" onclick='jt.appEdit()'>
                    <i class="fa fa-copy"></i>&nbsp;&nbsp;Duplicate
                </button>
              <button class="btn btn-outline-secondary btn-sm" onclick='jt.deleteApp()'>
                  <i class="fa fa-trash"></i>&nbsp;&nbsp;Delete
              </button>
          </div>

          <!-- APP TABS -->
          <ul class="nav nav-tabs hidden">
            <li class="nav-item">
              <div id='tab-app-view' class="nav-link subview-tab app-tabBtn" onclick='jt.setAppView("view");'>
                  <i class="fa fa-desktop"></i>&nbsp;&nbsp;Client
              </div>
            </li>
            <li class="nav-item">
              <div id='tab-app-preview' class="nav-link subview-tab app-tabBtn" onclick='jt.setAppView("preview");'>
                  <i class="fa fa-list"></i>&nbsp;&nbsp;App
              </div>
            </li>
          </ul>

          <div id='view-app-edit' class='subview app-tab hidden'>
              <div class="btn-group">
                  <button type="submit" class="btn btn-sm btn-outline-primary" onclick='jt.saveAppAndView();'>
                      <i class="fa fa-save"></i>&nbsp;Save and view
                  </button>
                  <button type="submit" class="btn btn-outline-secondary btn-sm" onclick='jt.saveApp();'>
                      <i class="fa fa-save"></i>&nbsp;Save
                  </button>
                  <button type="submit" class="btn btn-outline-secondary btn-sm" onclick='setView("app")'>
                      <i class="fa fa-times"></i>&nbsp;Cancel
                  </button>
              </div>

              <div class="form-group row">
                  <label for="edit-app-id" class="col-sm-2 col-form-label">Id</label>
                  <div class="col-sm-10">
                      <input type="text" style='max-width: 20rem;' class="form-control" id="edit-app-id" placeholder="Id">
                  </div>
              </div>

              // <div class="form-group row">
              //     <div class="col-sm-2 col-form-label">client.html</div>
              //     <div class='col-sm-10 col-form-label' id='edit-app-clienthtml' style='height: 30rem;'></div>
              // </div>

          </div>
          <view-app-preview></view-app-preview>
      </div>
      `;
    }
}

document.write('<script src="/admin/vue/webcomponents/ViewAppPreview.js"></script>');

jt.resizeIFrameToFitContent = function(iframe) {
    $(iframe).prop('height', null);
    iframe.height = iframe.contentWindow.document.documentElement.offsetHeight + 36;
    console.log('setting size to ' + iframe.width + ' / ' + iframe.height);
}

jt.appShowOptions = function() {
    jt.setEditAppOptionsData(appDefn, options, 'jt.saveSessionAppOptions()');
    $('#editAppOptionsModal').modal('show');
}

jt.openApp = function(appId) {
    var app = jt.app(appId);

    $('#edit-app-id').val(app.shortId);
    $('#view-app-id').text(app.shortId);
    $('#view-app-fullId').text(app.id);
    $('#view-app-appjs').text(app.appjs);
    $('#view-app-clienthtml').text(app.clientHTML);

    $('#editAppModal .modal-title').text(appId);

    jt.editor.reset();
    jt.editor.addFile('app.js', app.appjs, 'ace/mode/javascript');
    jt.editor.addFile('client.html', app.clientHTML, 'ace/mode/html');

    jt.editor.selectFile('app.js');

    jt.setEditAppOptionsData(app, app.options, jt.updateAppPreview);

    jt.updateAppPreview();

    $('#view-app-tree').empty();

    setView('app');
}

jt.appEdit = function() {
    $('#editAppModal').modal('show');
}

jt.deleteApp = function() {
    var appId = $('#view-app-fullId').text();
    jt.confirm(
        'Are you sure you want to delete App ' + appId + '?',
        function() {
            jt.socket.emit('deleteApp', appId);
        }
    );
}

jt.saveApp = function() {
    var app = {};
    app.origId = $('#view-app-fullId').text();
    app.id = $('#edit-app-id').val();
    var editor = ace.edit("edit-app-appjs");
    app.appjs = editor.getValue();

    var editorCH = ace.edit("edit-app-clienthtml");
    app.clientHTML = editorCH.getValue();

    jt.socket.emit('saveApp', app);

}

jt.saveAppAndView = function() {
    jt.saveApp();
    setView('app');
}

window.customElements.define('view-app', ViewApp);
